# Generated by Django 2.1.5 on 2019-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190506_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-id']},
        ),
    ]
