# Generated by Django 2.1.5 on 2019-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190412_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(-1, '#ff6666'), (0, '#ffff66'), (1, 'white')]),
        ),
    ]
