# Generated by Django 2.1.5 on 2019-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190412_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('#ff6666', 'Hign'), ('#ffff66', 'Middle'), ('white', 'Low')]),
        ),
    ]
