# Generated by Django 2.1.5 on 2019-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190412_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Hign'), (0, 'Middle'), (-1, 'Low')]),
        ),
    ]
