# Generated by Django 2.1.5 on 2019-04-12 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(-1, 'red'), (0, 'yellow'), (1, 'white')])),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (0, 'Uncompleted')], default=0)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
